### ISSUE TITLE
EOFError: Ran out of input

### ISSUE THREAD

**Issue by 7flash** [Sygil-Dev/nataili#11]
```
python bridge.py
```

```
INIT       | Downloading | Model: stable_diffusion
INIT       | OK          | Models
INIT       | OK          | Bridge Config
INIT       | Downloading | Model Reference
INIT       | OK          | Model Reference
INIT       | Loading     | stable_diffusion
Traceback (most recent call last):
  File "bridge.py", line 308, in <module>
    success = model_manager.load_model(model)
  File "/home/berliangur/ten18/AI-Horde/nataili/nataili/model_manager.py", line 206, in load_model
    self.loaded_models[model_name] = self.load_ckpt(model_name, precision, gpu_id)      
  File "/home/berliangur/ten18/AI-Horde/nataili/nataili/model_manager.py", line 149, in load_ckpt
    model = self.load_model_from_config(model_path=ckpt_path, config_path=config_path)  
  File "/home/berliangur/ten18/AI-Horde/nataili/nataili/model_manager.py", line 136, in load_model_from_config
    pl_sd = torch.load(model_path, map_location=map_location)
  File "/home/berliangur/.conda/envs/ldm/lib/python3.8/site-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)   
  File "/home/berliangur/.conda/envs/ldm/lib/python3.8/site-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input
```

**Comment by db0** [comment]
This likely means your download didn't work and somehow the md5sum didn't catch it. Did you try running again? Did you refresh the code recently?

**Comment by hlky** [comment]
Closing due to no response.

Seems related to incomplete download.

Reopen if issue reoccurs.
