### ISSUE TITLE
Getting WinError 126, The specified module could not be found. (shm.dll)

### ISSUE THREAD

**Issue by rtsonneveld** [Sygil-Dev/nataili#74]
After running horde-bridge.cmd I'm getting the following errors:

```
OSError: [WinError 126] The specified module could not be found. Error loading "D:\Software\nataili-main\nataili-main\conda\envs\windows\lib\site-packages\torch\lib\shm.dll" or one of its dependencies.
Traceback (most recent call last):
  File "bridge.py", line 7, in <module>
    from nataili.model_manager import ModelManager
  File "D:\Software\nataili-main\nataili-main\nataili\model_manager.py", line 7, in <module>
    import clip
  File "D:\Software\nataili-main\nataili-main\conda\envs\windows\lib\site-packages\clip\__init__.py", line 1, in <module>
    from .clip import *
  File "D:\Software\nataili-main\nataili-main\conda\envs\windows\lib\site-packages\clip\clip.py", line 8, in <module>
    import torch
  File "D:\Software\nataili-main\nataili-main\conda\envs\windows\lib\site-packages\torch\__init__.py", line 139, in <module>
    raise err
```

My system specs are as follows:
Windows 10 Pro (64-bit), build 19044.2251
32GB of RAM
AMD Ryzen 7 3700X 8-Core Processor                3.60 GHz
NVIDIA GeForce RTX 2080 SUPER (8GB)

**Comment by db0** [comment]
Yes I can replicate this on my end. I suspect some non-pinned library changed
